
#pragma once

/** NOTE: At one point I considered using a dependency-tick ordered system but
    honestly this creates a lot of complication and obscuring of control flow. I
    would really prefer if the code generated by this library were as
    straightforward and easy to follow as possible, which is why I don't really
    use inheritance at all.

    Such a system is minimally helpful in resolving bugs, so long as you HAVE a
    concept of a per-entity tick and are not just randomaly interleaving
    code. This can be enforced with a simple template interface checker trick.


    A single tick per-entity type is also not generic enough to fulfil the
    functions required. Or even 1 group of ticks per type, a type might be
    reused in different subsystems.
*/

namespace tyon
{

    template <typename t_entity>
    struct entity_uid
    {
        using t_self = entity_uid<t_entity>;
        i64 id;
        u128 uuid;

        CONSTRUCTOR entity_uid() = default;
        explicit constexpr
        CONSTRUCTOR entity_uid( i64 _id, u128 _uuid ) : id( _id ), uuid( _uuid ) {}
        explicit constexpr
        CONSTRUCTOR entity_uid( u128 _uuid ) : id(0), uuid( _uuid ) {}
        explicit constexpr
        CONSTRUCTOR entity_uid( i64 _id )
            : id(_id), uuid() { }
        explicit constexpr
        COPY_CONSTRUCTOR entity_uid( const t_self& arg )
            : id(arg.id), uuid(arg.uuid) { }
        COPY_CONSTRUCTOR entity_uid( const uid& arg )
            : id(arg.id), uuid(arg.uuid) { }

        explicit operator i64();

        PROC operator ==( t_self rhs ) -> bool
        {   return memory_same( this->uuid, rhs.uuid ); }

        PROC valid() -> bool
        {   auto empty = u128 {};
            return memory_different( this->uuid, empty );
        }

        PROC untyped_uid() -> uid
        {   return uid { id, uuid };
        }
    };

    /** SECTION: Attempt 2

        NOTE: I really didn't like the last system, it was really cumbersome to
        use when setting up new entities and didn't lend itself to disconnected
        instances of subsystems using the same or similar types.

        The internal mechanisms of the old system also looks weird to point it's
        obfuscated for the average person, and reading does not provide that
        much insight.

        I want this system to be simpler and focus more on convenience rather
        than being a monolithic system. And also to have simple and transparent
        internals.

        I wanted to create pseudo-global functions to allow accessing entities
        but those became singletons, which was not really what I wanted, and it
        also obfuscated the internals yet more. Perhaps generating a proxy
        objects to interact with entities makes more sense than using named
        functions.

        I think I also tried to make it  too much of an interface and forced the
        implimentation of tick()  init() and destroy() functions.  Which I ended
        up  not  using  in  practice  because   just  not  all  types  need  it,
        particularly  aggregate types,  which are  still useful  to treat  as an
        entity but  have no  real mandatory processing  functions. I  think it's
        still a good  idea having it as  an interface but forcing  it caused too
        much extra boilerplate.
    */

    template <typename T>
    struct entity_list
    {
        using t_uid = entity_uid<T>;
        array<T> entities;
    };

    /** NOTE: I wanted create the uuid on init but honestly it creates
        incoherent and sloppy logic if we do. All uids should just always be
        valid.  We can use some other mechanism for inactive entities.  Likely
        simply just "bool active" for most entities, but they can manage it
        themselves.
    */
    template <typename T>
    PROC entity_allocate( entity_list<T>* context ) -> T*
    {
        T* result = &context->entities.push_tail({});
        result->id = uuid_generate();
        return result;
    }

    template <typename T, typename t_proc>
    PROC entity_tick_all( entity_list<T>* context, t_proc tick_function ) -> void
    {
        i64 i_limit = context->entities.size();
        for (i64 i=0; i < i_limit; ++i)
        {
            tick_function( &context->entities[i] );
        }
    }

    template <typename T>
    PROC entity_search_id( entity_list<T>* context, uid id ) -> search_result<T>
    {
        bool null_id = (id.valid() == false);
        if (null_id) { return {}; }
        return context->entities.linear_search( [id]( T& arg ) {
            return arg.id == id; });
    }

    template <typename T>
    PROC entity_search_name( entity_list<T>* context, fstring name ) -> search_result<T>
    {
        bool null_arg = (name.empty());
        if (null_arg) { return {}; }
        return context->entities.linear_search( [name]( T& arg ) {
            return arg.name == name; });
    }

    template <typename T, typename t_proc>
    PROC entity_tick_all_array( array<T>* context, t_proc tick_function ) -> void
    {
        i64 i_limit = context->entities.size();
        for (i64 i=0; i < i_limit; ++i)
        {
            tick_function( &context->entities[i] );
        }
    }

    template <typename T>
    PROC entity_search_id_array( array<T>* context, uid id ) -> search_result<T>
    {
        return context->linear_search( [id]( T& arg ) {
            return arg.id == id; });
    }

    template <typename T>
    PROC entity_search_name_array( array<T>* context, fstring name ) -> search_result<T>
    {
        return context->linear_search( [&name]( T& arg ) {
            return arg.name == name; });
    }


}
